version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    build:
      context: ./mqtt
      dockerfile: ./Dockerfile
    restart: unless-stopped
  core:
    image: iqtlabs/edgetech-core:latest
    network_mode: "host"
    build:
      context: ./core
      dockerfile: ./Dockerfile
    depends_on: 
      - mqtt
  watchtower:
    image: containrrr/watchtower
    network_mode: "host"
    environment:
      - WATCHTOWER_POLL_INTERVAL:3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

