version: "3"
services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
  core:
    image: iqtlabs-edgetech-core:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
