version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:${SERVICES_VERSION:-latest}
    ports:
      - "1883:1883"
      - "9001:9001"
    build:
      context: ./mqtt
      dockerfile: ./Dockerfile
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
  core:
    image: iqtlabs/edgetech-core:${SERVICES_VERSION:-latest}
    network_mode: "host"
    build:
      context: ./core
      dockerfile: ./Dockerfile
    depends_on: 
      - mqtt
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
  watchtower:
    image: containrrr/watchtower:1.5.3
    network_mode: "host"
    environment:
      - WATCHTOWER_POLL_INTERVAL:3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval ${WATCHTOWER_POLL_INTERVAL:-3600}
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

