version: "3"
services:
  mqtt-broker:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    build:
      context: ./
      dockerfile: ./mqtt/Dockerfile
  core:
    image: iqtlabs/edgetech-core:latest
    build:
      context: ./
      dockerfile: ./core/Dockerfile
